### ISSUE TITLE
.gitignore missing in newly generated project

### ISSUE THREAD

**Issue by karpikpl** [kriasoft/babel-starter-kit#3] opened 2015-08-08 21:32 UTC
Hey,
when I generate new project with `yo javascript` the `.gitignore` file is always missing, even though I can see it in this repository.
Do you know why is that?
Is it because of how yo works?

**Comment by koistya** [comment] 2015-08-16 14:53
@karpikpl good catch! I will try to fix that.. I guess the problem is in this file:

https://github.com/kriasoft/babel-starter-kit/blob/yeoman-generator/app/index.js

The `.gitignore` files is ignored by default when you create an NPM package..

**Comment by koistya** [comment] 2015-08-16 18:35
@karpikpl thanks for the report! Fixed in [v0.1.0](https://www.npmjs.com/package/generator-javascript)

**Closed as completed by koistya** 2015-08-16 18:35 UTC
